//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genre
    {
        public Genre()
        {
            this.Musics = new HashSet<Music>();
        }
    
        public int GenreID { get; set; }
        public string Genre1 { get; set; }
    
        public virtual ICollection<Music> Musics { get; set; }
    }
}
