//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MusicChoiceEntities : DbContext
    {
        public MusicChoiceEntities()
            : base("name=MusicChoiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album> Albums { get; set; }
        public DbSet<Cast> Casts { get; set; }
        public DbSet<Composer> Composers { get; set; }
        public DbSet<Concert> Concerts { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<Music> Musics { get; set; }
        public DbSet<Performer> Performers { get; set; }
    
        public virtual ObjectResult<GetMusics_Result> GetMusics(ObjectParameter genreID, ObjectParameter composerID, ObjectParameter castID, ObjectParameter albumID, ObjectParameter performerID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMusics_Result>("GetMusics", genreID, composerID, castID, albumID, performerID);
        }
    }
}
