//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public Music()
        {
            this.Albums = new HashSet<Album>();
            this.Casts = new HashSet<Cast>();
            this.Concerts = new HashSet<Concert>();
            this.Performers = new HashSet<Performer>();
        }
    
        public int MusicID { get; set; }
        public string Music1 { get; set; }
        public Nullable<int> ComposerID { get; set; }
        public Nullable<int> GenreID { get; set; }
    
        public virtual Composer Composer { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Cast> Casts { get; set; }
        public virtual ICollection<Concert> Concerts { get; set; }
        public virtual ICollection<Performer> Performers { get; set; }
    }
}
